# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: 
 - main

pool:
  vmImage: ubuntu-latest

container:
  image: trufflesuite/ganache-cli:latest
  ports:
    - 8545

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
    checkLatest: true

- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true
    
- task: Yarn@3
  displayName: yarn install
  inputs:
    projectDirectory: 'ghd-upgradeable-bep20'
    arguments: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'ghd-upgradeable-bep20'
    customCommand: 'run  truffle:compile'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'ghd-upgradeable-bep20'
    customCommand: 'run  truffle:test'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'ghd-upgradeable-bep20'
    customCommand: 'run  stop-testrpc'


